spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${{ secrets.AWS_RDS_URL }}
    username: ${{ secrets.AWS_RDS_USERNAME }}
    password: ${{ secrets.AWS_RDS_PASSWORD }}

  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console
      show-sql: true

#  datasource:
#    url: jdbc:h2:mem:diary;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    defer-datasource-initialization: true
