spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://rds-diary-api.cgreiln2foqk.ap-northeast-2.rds.amazonaws.com:5432/postgres
#    username: postgres
#    password: 12121212
#
#  jpa:
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        ddl-auto: create
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      show-sql: true
#      properties:
#        hibernate:
#          format_sql: true

  datasource:
    url: jdbc:h2:mem:diary;NON_KEYWORDS=USER # h2의 예약어 user 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

#   insert data when application start
  jpa:
    defer-datasource-initialization: true
