insert into user (email, password, role, created_date) values ('hn', 'hn', 'USER', now());
insert into user (email, password, role, created_date) values ('hn2', 'hn2', 'ADMIN', now());
insert into user (email, password, role, created_date) values ('test@naver.com', '!@#QWEasdzxc', 'USER', now());
insert into post (title, content, view_count, is_delete, created_date, last_modified_date, user_id, origin, num, depth) values ('title1', 'Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', 0, false, now(), now(), 1, 1, 0, 0);
insert into post (title, content, view_count, is_delete, created_date, last_modified_date, user_id, origin, num, depth) values ('title2', 'Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', 0, false, now(), now(), 2, 2, 0, 0);
insert into post (title, content, view_count, is_delete, created_date, last_modified_date, user_id, origin, num, depth) values ('title3', 'Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', 0, false, now(), now(), 3, 3, 0, 0);
insert into comment (origin, user_id, post_id, is_delete, content, created_date, last_modified_date, depth) values (1, 1, 1, false, 'comment-Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', now(), now(), 0);
insert into comment (origin, user_id, post_id, is_delete, content, created_date, last_modified_date, depth) values (2, 2, 1, false, 'comment-Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', now(), now(), 0);
insert into comment (origin, user_id, post_id, is_delete, content, created_date, last_modified_date, depth) values (3, 3, 1, false, 'comment-Florivax jumblemix trivion blazzify flibberjack sprogle buzzlenook zyptonic klazmatic crungleflap splixify zorptical glibberwocky plixionaire whizzleton scrimbleflux drazzleton xyptonic fuzzlenook splindarify zappleton jibberflux krinkleton.', now(), now(), 0);
